### ISSUE TITLE
After Call Ringing Bug

### ISSUE THREAD

**Issue by titaniumtux** [ringcentral/ringcentral-embeddable-electron-app#69] opened 2023-02-04 02:02 UTC
Using on Kubuntu 22.04. After a call or transferring a call from the desktop app to the mobile client, I would get a ringing sound from the desktop app about half the time.

**Comment by embbnux** [comment] 2023-02-07 03:52
hi @titaniumtux Do you using same account int the desktop and mobile client? If that, you need to check the call handling settings in RingCentral service portal.  By default, it is ringing all once. So all devices with same account will ring.

https://service.ringcentral.com/application/settings/settings/callHandling/userHours
<img width="994" alt="image" src="https://user-images.githubusercontent.com/7036536/217143689-c85cd754-fedb-492f-8485-dead2f97d6b4.png">

**Comment by embbnux** [comment] 2023-02-07 03:57
Ohh, I get your another message in https://github.com/ringcentral/ringcentral-community-app/issues/41
So it is the issue that the app keep ringing event there are no calls in the app? 
It should be a bug, let me check more, it seems that the app fail to get the message that call is ended. 
Thanks for feedback this to us.

**Comment by embbnux** [comment] 2023-02-07 03:59
And can you help to check if call handling setting "Ring in order" can help to resolve this.

**Comment by titaniumtux** [comment] 2023-02-07 04:22
@embbnux how do I verify the "Ring in order" in the app? I think it rings in all places at once, which I don't mind. The issue is after the call though.

**Comment by embbnux** [comment] 2023-02-07 07:49
After you set "Ring in order", the call will only ringing in a device at once. After a device cancel ringing, it will ringing in another device.
And can you also help to check if the issue happens at call from call queue or now?
The "community app" on Linux also run in same web phone SDK, let me check if there are any version upgrading issue.

**Comment by titaniumtux** [comment] 2023-02-07 07:55
@embbnux I don't use call queue at all.

**Comment by embbnux** [comment] 2023-02-07 09:11
Hi @titaniumtux Can you help to check if the issue can be still reproduced in your side.
We made some updates in this app's web resource to use same SDK version as "RC community app". You can get the update after you restart the app (Ctrl+Q to quit). And I can't reproduce this in my side. If it still exists, maybe need your more help to collect client side logs.

**Comment by titaniumtux** [comment] 2023-02-08 05:48
@embbnux I did quit and restart the embedded app. After I received an incoming call that I did not pick up, the app kept perpetually ringing on my computer (presumably for a few hours).

**Comment by embbnux** [comment] 2023-02-08 07:33
Hi @titaniumtux Thanks for confirming this. Can you help to collect client side logs and send to us, it can help us track the issue.

To collect logs:
1. Logout in the app, then quit to app by Ctrl+Q
2. In terminal, run "DEBUG=1 ringcentral-embeddable-voice" to start app in DEBUG mode
3. Adjust the window size to get UI like this 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/7036536/217461017-085c282c-318e-4c4d-93da-c60b1403ff10.png">
4. Login with your RC account and reproduce the issue.

5. Go to developer tool's Network panel
6. Right click network request and click "Save all as HAR with content" to get HAR logs
<img width="438" alt="image" src="https://user-images.githubusercontent.com/7036536/217461646-ef0e9471-872f-4f0d-8136-ecfa9e031187.png">
7. Go to developer tool's Console panel
8. Right click log and click "Save as" to get console logs
<img width="433" alt="image" src="https://user-images.githubusercontent.com/7036536/217462021-aed95fec-a174-49eb-90f9-57e90f39576d.png">

And please send the log by creating a ticket in https://developers.ringcentral.com/support/create-case and share ticket name here.

**Comment by titaniumtux** [comment] 2023-02-08 18:32
@embbnux case number 17497048. Thank you for the detailed instructions! I was able to attach the .log file, but the .HAR file was too large. How can I upload the .HAR file?

**Comment by titaniumtux** [comment] 2023-02-09 04:03
@embbnux here's the file: [uploaded to IberBox](https://iberbox.com/file/snUaZbfj71u20uNz1yjwPw#CzW_6IVUYA4PDcVd7p5Z29Da-S9kUw1XDMwf8K1AAaY)

**Comment by embbnux** [comment] 2023-02-09 09:21
HI @titaniumtux I have got the har file, please remove your comment link to avoid user data leak.

**Comment by embbnux** [comment] 2023-02-09 09:39
Oh, I have permission to remove that.

**Comment by embbnux** [comment] 2023-02-09 09:40
For more logs, let's share with the case and email to protect your data.

**Comment by titaniumtux** [comment] 2023-02-09 15:49
Sounds great @embbnux

**Comment by embbnux** [comment] 2023-02-16 02:41
link related issue https://github.com/ringcentral/ringcentral-web-phone/issues/284 
The audio is only paused, and not removed. And sometime, the audio is not paused successfully to cause this issue.
To have a quick fix, user can use the media player feature in desktop to stop the ringing.
<img width="572" alt="image" src="https://user-images.githubusercontent.com/7036536/219254219-005d83ba-e6d1-4a15-a0d7-c45ab2b58139.png">

**Comment by embbnux** [comment] 2023-03-02 00:59
Closed this as we fixed this with https://github.com/ringcentral/ringcentral-embeddable/pull/677

**Closed by embbnux** 2023-03-02 00:59 UTC
Labels: bug
