### ISSUE TITLE
Phone number is not copied, when clicking on tel: links in Firefox

### ISSUE THREAD

**Issue by WeAreGeek** [ringcentral/ringcentral-embeddable-electron-app#22] opened 2020-06-17 12:57 UTC
When opening a tel: link from Firefox, the phone number is not copied to the app. The Ringcentral app opens, but I have to enter the phone number manually. I was unable to test this in other browsers as of yet.

**Comment by embbnux** [comment] 2020-06-18 07:25
Thanks @WeAreGeek , I think this app doesn't support tel: link from browser now. I will investigate on how to support it.

**Comment by embbnux** [comment] 2020-07-27 12:07
hi @WeAreGeek We released 0.1.5 to support this. Can you help to try it?

**Comment by embbnux** [comment] 2020-08-03 02:55
close by inactive. Feel free to reopen it.

**Comment by mzguy** [comment] 2021-04-13 17:50
This isn't working for me. Same issue: app opens but phone number isn't populated in the dialer. I'm running version 0.1.6 in a Snap on Ubuntu 20.04 LTS. I have the app set to RingOut mode.

**Comment by embbnux** [comment] 2021-04-16 07:07
> This isn't working for me. Same issue: app opens but phone number isn't populated in the dialer. I'm running version 0.1.6 in a Snap on Ubuntu 20.04 LTS. I have the app set to RingOut mode.

Do you click the link in Firefox or Chrome. I try Chrome, it doesn't work, but work at Firefox. 
And can you provide your Browser version information to help us track the issue?

**Comment by embbnux** [comment] 2021-04-16 07:10
link related issue https://github.com/electron-userland/electron-builder/issues/4035

**Comment by mzguy** [comment] 2021-04-19 18:03
Firefox 87.0

**Comment by embbnux** [comment] 2021-04-21 02:17
@mzguy can you help to check app settings in your system as my screenshot in upper comment. I want to check if links are added successfully.

**Comment by mzguy** [comment] 2021-04-23 19:58
@embbnux Sorry, I may have missed your screenshot initially. My Default Handlers section looks exactly like your screenshot.

**Comment by embbnux** [comment] 2021-04-26 08:32
Hi @mzguy, so you have "tel://" link in Links setting? If you have it, it should be issue in Firefox. You can try to reinstall Firefox to make it work. 
When the app register the link, Firefox should pop up app selection window:
![image](https://user-images.githubusercontent.com/7036536/116053050-d4d13c00-a6ac-11eb-9cf4-e5a7b0b06298.png)

**Comment by mzguy** [comment] 2021-04-26 15:17
I have that prompt. I select RingCentral, and the app opens. The problem is that it doesn't pre-populate the phone number.

Is the app set up to accept tel links and pre-fill the phone number for dialing?

**Comment by embbnux** [comment] 2021-04-30 12:28
> I have that prompt. I select RingCentral, and the app opens. The problem is that it doesn't pre-populate the phone number.
> 
> Is the app set up to accept tel links and pre-fill the phone number for dialing?

Thanks @mzguy I can reproduce in my side now. Let me fix it.

**Comment by embbnux** [comment] 2021-04-30 13:43
@mzguy after some investigation, we found it is issue at snap package. For now, you can install deb package to make it work.
I will keep it updated once it is fixed at snap package.

**Comment by mzguy** [comment] 2021-06-25 21:56
Has a fix been put in yet?

**Comment by embbnux** [comment] 2021-06-30 09:09
@mzguy Released 0.1.8 to fix this issue.

**Comment by mzguy** [comment] 2021-06-30 18:08
Still doesn't work on 0.1.8

**Comment by embbnux** [comment] 2021-07-01 02:55
Hi @mzguy Can you share how you install this app and check current version. You can get version at Setting page. 
Currently, I tested at Ubuntu 20.04.2 LTS with snap package.
![image](https://user-images.githubusercontent.com/7036536/124057744-a67c2e00-da5a-11eb-8896-50287ee3d1da.png)

**Comment by mzguy** [comment] 2021-07-02 18:35
Same as you. It's a Snap installed via Ubuntu Software on 20.04 LTS.
Settings confirm version 0.1.8. Tel: links open the app, but there's no
phone number. Just before the empty dialpad appears, I see some text flash
in the RingCentral app window for a brief instant. It appears to be some
sort of error, but it's on screen a very short time, so I can't read it
clearly. However, I do see something like "MeetingStatus - ScheduleSuccess"
and below that "CopyToClipboard".

**Comment by embbnux** [comment] 2021-07-04 07:49
@mzguy can you try to remove the app, then reinstall it to find if it can be fixed?

**Comment by mzguy** [comment] 2021-11-14 16:54
I finally had some time to look into this more.

The dialing works from the terminal using 'xdg-open tel://1234567', but fails when clicking on the same link from within Firefox. The app still opens, but the RingOut dialing doesn't occur.

**Comment by mzguy** [comment] 2021-11-15 22:55
Ok, very strange. The above worked apparently only because I had just reinstalled. It seems to work once on reinstall, then never again!

**Comment by embbnux** [comment] 2021-11-16 02:49
Hi @mzguy You mean that the tel link only work for Browser mode calling, and not work for RingOut?
Let me check that. Thanks for feedback

**Comment by embbnux** [comment] 2021-11-16 03:03
Hi @mzguy I can reproduce with your steps. it will be fixed it soon.

**Comment by embbnux** [comment] 2021-11-16 05:43
Hi @mzguy It should be fixed after you reopen the app. As it loads HTML from Github Page, it may have some cache delay time.

**Comment by mzguy** [comment] 2021-11-16 18:47
@embbnux Thanks, it works!

**Comment by embbnux** [comment] 2021-11-17 02:42
> @embbnux Thanks, it works!

Cool! Thanks for confirming.

**Comment by mzguy** [comment] 2024-02-23 18:54
I haven't tested this in a while, but I'm on version 0.3.0 now, and the problem has returned. The app opens with an empty number field, so it isn't pre-populated.

**Comment by mzguy** [comment] 2024-02-27 18:49
@embbnux I think an update caused it to revert to previous behavior? Can you replicate again? As before, the number gets populated the first time after starting the app and clicking on a tel: link, but any future clicks result in no number showing up.

**Comment by embbnux** [comment] 2024-02-29 02:42
Thanks @mzguy for reporting this. Let me reopen it. It should be issue caused by electron upgrading.

**Comment by embbnux** [comment] 2024-03-04 08:37
hi @mzguy we have a new release 0.3.1 for the fix. https://github.com/ringcentral/ringcentral-embeddable-electron-app/releases

**Comment by embbnux** [comment] 2024-03-05 02:54
i am going to close this. Feel free to reopen it.

**Closed by embbnux** 2024-03-05 02:54 UTC
Labels: enhancement
